### ISSUE TITLE
关于netty的一个问题

### ISSUE THREAD

**Issue by labmem** [yongshun/learn_netty_source_code#1]
从segmentfault过来的，sf的登录系统有问题，登录不上。
想请教一个问题，我已经在stackoverflow上提问了，但还没有人回答：
http://stackoverflow.com/questions/40482830/is-there-a-possibility-that-pipeline-firechannelactive-is-executed-twice-when
望指教，谢谢。

**Comment by yongshun** [comment]
这个问题挺有趣的, 三言两语讲不清楚, 我写了一篇文章 https://segmentfault.com/a/1190000007422683, 在这篇文章中详细分析了你所提出的问题.

**Comment by yongshun** [comment]
这个问题挺有趣的, 三言两语讲不清楚, 我写了一篇文章 https://segmentfault.com/a/1190000007422683,
在这篇文章中详细分析了你所提出的问题.

2016-11-08 19:29 GMT+08:00 labmem notifications@github.com:

**Comment by labmem** [comment]
非常明白地解答了我的疑惑。写了这么长一篇文章来解释，辛苦了！多谢！

**Comment by yongshun** [comment]
客气
