### ISSUE TITLE
楼主怎么停更了，等着看呢

### ISSUE THREAD

**Issue by clpsz** [yongshun/learn_netty_source_code#2]

**Comment by SuperChrisliu** [comment]
排队等待Netty 源码分析之 四 Promise 与 Future: 双子星的秘密

**Comment by wokaole** [comment]
排队等待Netty 源码分析之 四 Promise 与 Future: 双子星的秘密

**Comment by WinneShen** [comment]
排队等待Netty 源码分析之 四 Promise 与 Future: 双子星的秘密

**Comment by fzp0723** [comment]
排队等待Netty 源码分析之 四 Promise 与 Future: 双子星的秘密

**Comment by limingyao** [comment]
排队等待Netty 源码分析之 四 Promise 与 Future: 双子星的秘密

**Comment by laihaotao** [comment]
排队等待Netty 源码分析之 四 Promise 与 Future: 双子星的秘密
